apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-deployer
  namespace: echo-dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: echo-dev
  name: deployer-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-deployer
  namespace: echo-dev
subjects:
  - kind: ServiceAccount
    name: ci-deployer
    namespace: echo-dev
roleRef:
  kind: Role
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io
